### ISSUE TITLE
Can't locate object method "mkdir" via package "Path::Tiny"

### ISSUE THREAD

**Issue by eserte** [uperl/Data-Section-Pluggable#7]
The test suite fails on some of my smoker systems:
```
Can't locate object method "mkdir" via package "Path::Tiny" at /home/cpansand/.cpan/build/2024121816/Data-Section-Pluggable-0.04-0/blib/lib/Data/Section/Pluggable.pm line 184, <DATA> line 2.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 after test #4.
t/data_section_pluggable.t .............................. 
Dubious, test returned 255 (wstat 65280, 0xff00)
All 4 subtests passed 
```
Probably a minimum prereq version for Path::Tiny is needed.

**Comment by plicease** [comment]
I believe this should be fixed in 0.05.  I haven't been able to test this, but judging from the `Changes` file Looks like 0.130 is the magic number.  The previous version introduced `->mkdir` but that version has bug fixes for it :).

Thank you for reporting this.   I've also added this to by dzil bundle:
https://github.com/uperl/Dist-Zilla-PluginBundle-Author-Plicease/commit/4a434d210627f7cfdb1302170814ec4e09dcda89
since I tend to use that feature a lot and without it will be easy to forget.
